# Generated by Django 5.0.1 on 2024-01-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
